Feature/multi checkbox
nirmit-sawhney/Javascript_Challenges pull request #4
Opened 2022-06-21 07:41 UTC by nirmit-sawhney

Done with the challenge. Enabled all the features mentioned. Kindly check and let me know for any change.

Link to the challenges index,
[https://nirmit-sawhney.github.io/Javascript_Challenges/](url)

2022-06-21 07:59 UTC, vrknetha requested changes

2022-06-21 07:59 UTC, vrknetha commented on multi_checkbox/app.js
> +//     id: 8,
no comments should be there in code

2022-06-21 08:04 UTC, nirmit-sawhney commented on multi_checkbox/app.js
> +//     id: 8,
@vrknetha Done with changes.

2022-06-22 11:02 UTC, ManojSalugu approved these changes

2022-06-22 11:05 UTC, merged